services:
  # Product Database
  product-db:
    image: postgres:18
    container_name: product-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nabin99
      POSTGRES_DB: product-service
    volumes:
      - ./product-data:/var/lib/postgresql

  # Order Database
  order-db:
    image: postgres:18
    container_name: order-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nabin99
      POSTGRES_DB: order-service
    volumes:
      - ./order-data:/var/lib/postgresql