spring.application.name= inventory-service

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/inventory-service
spring.datasource.username=postgres
spring.datasource.password=nabin99

# JDBC Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Show SQL in console (optional but useful)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG

# JSON handling (important for your Map field)
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

#port configuration
server.port=8082

jwt.secret=mySuperSecretKeyForJwtAuthentication12345678901234567890
jwt.expiration=86400000